### ISSUE TITLE
Fingerprint quality coming very low

### ISSUE THREAD

**Issue by adnanAliSDE** [VikashAnandJha/MantraMFS100#1]
I have used your custom made sdk and I am capturing fingerprints through your code. Fingerprits are being captured but the quality is not sufficient enough for my work please see my code and help that how can I improve the quality of captured fingerprints. Please take a look at: https://github.com/adnanAliSDE/lms-fingerprints](url)

**Comment by VikashAnandJha** [comment]
Please use this function and pass the proper value of quality from 0-100
>  CaptureFinger(quality, timeout)

**Comment by adnanAliSDE** [comment]
Yes I tried that there wasn't any issue of quality.In my application when I passed fingerprint data then I inverted the image horizontally then it worked.
