### ISSUE TITLE
Want help to integrate the mantra mfs100 in my application

### ISSUE THREAD

**Issue by thesarinjaizz09** [VikashAnandJha/MantraMFS100#2]
Hey i saw your custom sdk for the mantra mfs100. My question is how do i use that sdk with mantra. I have installed the rd service sdk from the official mantra website. Can you please guide me what to do next as it will help me to finish my college project. Please...

**Comment by VikashAnandJha** [comment]
The current sdk codes are outdated. Please contact mantra support

**Comment by VikashAnandJha** [comment]
> Hey i saw your custom sdk for the mantra mfs100. My question is how do i use that sdk with mantra. I have installed the rd service sdk from the official mantra website. Can you please guide me what to do next as it will help me to finish my college project. Please...

The current sdk codes are outdated. Please contact mantra support
